version: '3.8'

services:
  # Database
  mysql:
    image: mysql:8.0
    container_name: aplikasi_sekolah_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: aplikasi_sekolah
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - aplikasi_sekolah
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      timeout: 20s
      retries: 10

  # Backend Laravel
  backend:
    build: ./backend
    container_name: aplikasi_sekolah_backend
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/storage/app/public:/var/www/public/storage
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - aplikasi_sekolah
    environment:
      - APP_NAME=Laravel
      - APP_ENV=production
      - APP_KEY=
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=aplikasi_sekolah
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password

  # Frontend React
  frontend:
    build: ./frontend
    container_name: aplikasi_sekolah_frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - aplikasi_sekolah
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000/api

volumes:
  mysql_data:

networks:
  aplikasi_sekolah:
    driver: bridge 